[package]
name = "camo"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
lnk = "0.5.1"
mslnk = "0.1.8"
obfstr = "0.4.4"
rand = "0.9.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
serde_json = "1.0.140"
sha256 = "1.6.0"
sha2 = "0.10"
clap = "3.0"
chrono = "0.4"